name: adversarial-object-segmentation
channels:
  - pytorch
  - soumith
  - conda-forge
  - defaults
dependencies:
  - av=0.4.0
  - bzip2=1.0.6
  - certifi=2018.4.16
  - ffmpeg=3.2.4
  - libiconv=1.15
  - openssl=1.0.2o
  - x264=20131218
  - asn1crypto=0.24.0
  - blas=1.0
  - bokeh=0.12.15
  - ca-certificates=2018.03.07
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.5.2
  - cryptography=2.2.2
  - cycler=0.10.0
  - cython=0.28.2
  - cytoolz=0.9.0.1
  - dask=0.17.4
  - dask-core=0.17.4
  - dbus=1.13.2
  - decorator=4.3.0
  - distributed=1.21.8
  - expat=2.2.5
  - fontconfig=2.12.6
  - freetype=2.8
  - glib=2.56.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - heapdict=1.0.0
  - icu=58.2
  - idna=2.6
  - imageio=2.3.0
  - intel-openmp=2018.0.0
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libpng=1.6.34
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - locket=0.2.0
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - msgpack-python=0.5.6
  - ncurses=6.1
  - networkx=2.1
  - ninja=1.8.2
  - numpy=1.14.3
  - numpy-base=1.14.3
  - olefile=0.45.1
  - packaging=17.1
  - pandas=0.22.0
  - partd=0.3.8
  - pcre=8.42
  - pillow=5.1.0
  - pip=10.0.1
  - psutil=5.4.5
  - pycparser=2.18
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.4
  - pywavelets=0.5.2
  - pyyaml=3.12
  - qt=5.9.5
  - readline=7.0
  - requests=2.18.4
  - scikit-image=0.13.1
  - scipy=1.1.0
  - setuptools=39.1.0
  - sip=4.19.8
  - six=1.11.0
  - sortedcontainers=1.5.10
  - sqlite=3.23.1
  - tblib=1.3.2
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.0.2
  - urllib3=1.22
  - wheel=0.31.0
  - xz=5.2.3
  - yaml=0.1.7
  - zict=0.1.3
  - zlib=1.2.11
  - torchvision=0.2.0
  - cuda91=1.0
  - pytorch=0.3.1
  - pip:
    - torch==0.3.1.post2
